property_codes:
  BD: 1
  C:N: 2
  CCE: 3
  cf: 4
  Clay: 5
  Ec: 6
  Ece: 7
  PH: 8
  PMC: 9
  Sand: 10
  SC: 11
  Silt: 13
  SOC: 14
  SOC stock: 15
  SOM: 16
  Total C: 17
  Total N: 18
  Total S: 19
